
import { type LucideIcon } from 'lucide-react';

export interface BaseMediaItem {
  slug?: string;
  title: string;
  description: string;
  icon?: string;
  isZoomable?: boolean;
}

export interface PhotoMedia extends BaseMediaItem {
  type: 'photo';
  source: string | string[]; // Can be a single image or an array for rotation
  dataAiHint?: string;
  prompt?: string;
}

export interface VideoMedia extends BaseMediaItem {
  type: 'video';
  image: string; // Thumbnail image
  embedUrl: string;
  dataAiHint?: string;
}

export interface CodeMedia extends BaseMediaItem {
  type: 'code';
  code: string;
  mockupUrl: string;
}

export type MediaItem = PhotoMedia | VideoMedia | CodeMedia;

const allMedia: MediaItem[] = [
  // AI Art Collection
  {
    slug: 'ai-art-collection',
    type: 'photo',
    icon: 'bot',
    title: 'AI Artwork Collection',
    description: 'A diverse collection of visuals generated by neural networks interpreting creative prompts. Explores various styles from abstract to photorealistic.',
    source: [
      '/images/AI_History_010.jpeg',
      '/images/AI_History_023.jpeg',
      '/images/AI_History_051.jpeg',
      '/images/AI_History_054.jpeg',
      '/images/AI_History_059.jpeg',
      '/images/AI_Art_Fashion051.jpeg',
      '/images/AI_Art_Fashion060.jpeg',
      '/images/AI_Art_Fashion070.jpeg',
      '/images/AI_Art_Fashion080.jpeg',
      '/images/AI_Art_Fashion090.jpeg',
      '/images/AI_Art_Culture001.jpeg',
      '/images/AI_Art_Culture010.jpeg',
      '/images/AI_Art_Culture020.jpeg',
      '/images/AI_Art_Culture030.jpeg',
      '/images/AI_Art_Culture040.jpeg',
      '/images/AI_Medical_Science_001.jpeg',
      '/images/AI_Medical_Science_015.jpeg',
      '/images/AI_Medical_Science_030.jpeg',
      '/images/AI_Medical_Science_045.jpeg',
      '/images/AI_Medical_Science_060.jpeg',
    ],
    dataAiHint: 'abstract neural network',
    prompt: 'A vibrant, swirling nebula of cosmic dust and stars, in the style of a watercolor painting.',
    isZoomable: true,
  },
  // Original Art
  {
    slug: 'original-art',
    type: 'photo',
    icon: 'image',
    title: 'Original Artwork',
    description: 'A digital painting created with a focus on color theory and composition.',
    source: '/images/AI_Animee_144.jpeg',
    dataAiHint: 'digital art canvas',
    isZoomable: true,
  },
  // Videos
  {
    slug: 'video-1',
    type: 'video',
    icon: 'playCircle',
    title: 'AI-Generated Animation',
    description: 'An abstract animation generated by an AI video model.',
    image: '/images/project_006.png',
    embedUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ', // Placeholder
    dataAiHint: 'abstract animation',
  },
  {
    slug: 'video-2',
    type: 'video',
    icon: 'playCircle',
    title: 'Portfolio Reel',
    description: 'A showcase of various motion graphics and visual effects.',
    image: '/images/project_007.png',
    embedUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ', // Placeholder
    dataAiHint: 'motion graphics',
  },
  // Report as Code
  {
    slug: 'Tailwind-tecnical-report', // Matches the slug in blog posts
    type: 'report',
    icon: 'code2',
    title: 'Interactive Tailwind CSS Report',
    description: 'A live demonstration of a UI component built with React and Framer Motion.',
    // These properties align it with PostMeta for the union type
    isHtml: true,
    date: '2024-07-29', // Example date
    tags: ['Interactive', 'Report', 'CSS'],
    image: '/images/posts/Tailwind-tecnical-report.png'
  },
];


// Simulate an async fetch
export const getMedia = async (): Promise<MediaItem[]> => {
  return Promise.resolve(allMedia);
};
